- schema/codec_test.go
- schema/qualified/base/codec_test.go
- schema/qualified/base/document_test.go
- schema/qualified/base/immutables_test.go
- schema/qualified/base/mutables_test.go
- schema/qualified/codec_test.go
- schema/types/base/codec_test.go
- schema/types/base/height_test.go
- schema/types/base/signature_test.go
- simulation/schema/types/base/data_test.go
- simulation/schema/types/base/id_test.go
- simulation/schema/types/base/properties_test.go
- simulation/schema/types/base/property_test.go
- simulation/utilities_test.go
Changes made on schema/types. Code convergence is 100%.
> Changes made on schema/types

- schema/types/base/height.go
- schema/types/height.go
Closes: #26 
NewHeight() method converts any input smaller than -1 to -1.
> fix: issue #26 NewHeight() accepts -ve values(schema)

- .github/workflows/test.yml
- Makefile
Closes: #XXXX
---
I have...
I have...
> ci: coverage report on test failure

- modules/identities/internal/key/identityID.go
- schema/parameters/base/parameter_test.go
Closes: #33
Adding nil check to constructor, temp fix.
> fix(identities): adding nil check on IdentityID constructor.

- schema/data/base/listData.go
Closes: #29 
adding nil check on generateHash method
> fix(schema): issue#29 adding nil check on generateHash method

- modules/classifications/internal/key/utilities.go
> fix(classifications): fixing incorrect nil check

- modules/assets/internal/parameters/dummy/validator_test.go
- modules/identities/internal/key/utilities_test.go
- modules/identities/internal/parameters/dummy/validator_test.go
- schema/data/base/listData_test.go
- schema/helpers/base/auxiliary_test.go
- schema/parameters/base/parameter_test.go
unit test for issue#27,28,30,31,32,35,36
Closes: #XXXX
modules/assets/internal/parameters/dummy/validator_test.go
modules/identities/internal/key/utilities_test.go
modules/identities/internal/parameters/dummy/validator_test.go
schema/data/base/listData_test.go
schema/helpers/base/auxiliary_test.go
schema/parameters/base/parameter_test.go
---
I have...
I have...
> test(base,key,dummy): add unit test for issue#27,28,30,31,32,35,36

- schema/data/base/idData.go
- schema/ids/base/id.go
- schema/parameters/base/parameter.go
- schema/parameters/base/parameter_test.go
Closes: #36 
adding ID comparison to compare parameter
> fix(parameter): issue#36

- schema/data/base/idData.go
- schema/data/base/listData_test.go
- schema/ids/base/id.go
- schema/parameters/base/parameter.go
- schema/parameters/base/parameter_test.go
closing TODO linked to invalid issue
> fix(test): closing issue#30

- modules/assets/internal/parameters/dummy/validator.go
- modules/assets/internal/parameters/dummy/validator_test.go
- modules/classifications/internal/parameters/dummy/validator.go
- modules/identities/internal/parameters/dummy/validator.go
- modules/maintainers/internal/parameters/dummy/validator.go
- modules/metas/internal/parameters/dummy/validator.go
- modules/orders/internal/parameters/dummy/validator.go
- modules/splits/internal/parameters/dummy/validator.go
- schema/data/base/idData.go
- schema/data/base/listData_test.go
- schema/helpers/base/auxiliary_test.go
- schema/ids/base/id.go
- schema/parameters/base/parameter.go
- schema/parameters/base/parameter_test.go
Closes: #32
removing type cast
> fix(parameter): issue#32 removing type cast

- schema/data/base/accAddressData_test.go
- schema/data/base/booleanData_test.go
- schema/ids/base/dataID_mock.go
- schema/ids/base/dataID_test.go
- schema/lists/base/dataList_test.go
- schema/lists/base/idList_test.go
- schema/lists/base/list_test.go
- schema/lists/base/metaPropertyList_test.go
- schema/lists/base/propertyList_test.go
- schema/lists/base/stringDataMock.go
Test Files for 
schema/lists/*
schema/ids/*
schema/data/*
---
I have...
I have...
> test(schema): tests for ids Lists

- schema/lists/utilities/metaPropertyList_test.go
- schema/lists/utilities/propertyList_test.go
- schema/properties/base/metaProperty_test.go
- schema/properties/base/property_test.go
- schema/properties/base/stringDataMock.go
- schema/properties/utilities/metaProperty_test.go
Added unit test for:
schema/lists/*
schame/ids/*
schema/properties/*
I have...
I have...
> test(schema): add missing unit test for schema

- README.md
Signed-off-by: pratikbin <68642400+pratikbin@users.noreply.github.com>
Closes: #XXXX
---
I have...
I have...
> fix(docs): youtube channel link

- .github/CODEOWNERS
- README.md
Closes: #XXXX
---
I have...
I have...
> fix: add codeowner, add ig and telegram link in docs

- modules/maintainers/internal/key/key_test.go
- modules/maintainers/internal/mappable/mappable_test.go
- modules/maintainers/internal/parameters/prototype_test.go
- modules/maintainers/internal/queries/maintainer/keeper_test.go
- modules/maintainers/internal/queries/maintainer/request_test.go
Adds tests for maintainer keepers
Closes: #XXXX
---
I have...
I have...
correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR …
> tests for maintainers keepers

- .github/CODEOWNERS
Require either person for any files changes 
---
I have...
I have...
correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR …
> fix(codeowner): require either for * changes

- modules/assets/internal/parameters/dummy/validator_test.go
- modules/assets/internal/queries/asset/request_test.go
- modules/assets/internal/transactions/burn/keeper_test.go
- modules/assets/internal/transactions/renumerate/keeper_test.go
- modules/classifications/auxiliaries/member/request_test.go
- modules/identities/internal/queries/identity/request_test.go
- modules/identities/internal/queries/prototype_test.go
- modules/identities/internal/transactions/define/message_test.go
- modules/identities/internal/transactions/define/request_test.go
- modules/identities/internal/transactions/deputize/request_test.go
- modules/identities/internal/transactions/issue/request_test.go
- modules/identities/internal/transactions/mutate/request_test.go
- modules/identities/internal/transactions/revoke/keeper_test.go
- modules/identities/internal/transactions/revoke/request_test.go
- modules/maintainers/auxiliaries/verify/keeper_test.go
- modules/maintainers/internal/mappable/mappable_test.go
- modules/metas/auxiliaries/supplement/keeper_mock.go
- modules/metas/auxiliaries/supplement/keeper_test.go
- modules/orders/internal/transactions/cancel/keeper_test.go
- modules/orders/internal/transactions/prototype_test.go
- schema/data/base/heightData_test.go
- schema/data/base/listData_test.go
- schema/lists/base/dataList_test.go
- schema/lists/base/idList_test.go
- schema/lists/base/list_test.go
- schema/properties/base/mesaProperty_test.go
- schema/properties/base/metaProperty_test.go
update tests for latest Master changes
Closes: #XXXX
---
I have...
I have...
correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the …
> master test fixes

- modules/maintainers/auxiliaries/deputize/keeper_test.go
- modules/maintainers/auxiliaries/deputize/request_test.go
- modules/maintainers/auxiliaries/maintain/keeper_test.go
- modules/maintainers/auxiliaries/maintain/request_test.go
- modules/maintainers/auxiliaries/revoke/keeper_test.go
- modules/maintainers/auxiliaries/revoke/request_test.go
- modules/maintainers/auxiliaries/super/keeper_test.go
- modules/maintainers/auxiliaries/super/request_test.go
- modules/maintainers/auxiliaries/verify/request_test.go
add maintainer tests for auxiliaries
Closes: #XXXX
---
I have...
I have...
correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the …
> add maintainer tests for auxiliaries

- modules/identities/internal/transactions/issue/request_test.go
- schema/lists/base/propertyList_test.go
- schema/properties/base/metaProperty_test.go
Closes: #XXXX
---
I have...
I have...
> Additional test fixes

- modules/classifications/auxiliaries/define/keeper_test.go
Adding Few more tests and optimising input generation
Closes: #XXXX
---
I have...
I have...
correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/inde …
> test(classification): update tests for define classification keeper

- schema/helpers/base/transaction.go
- schema/lists/base/dataList.go
- schema/lists/base/dataList_test.go
Closes: #156
Closes: #63 
---
I have...
I have...
> `baseReq` sanitization before `MakeMsg`

- Makefile
- utilities/rest/queuing/signAndBroadcast.go
Closes: #XXXX
---
I have...
I have...
> adding make file command for installing all buf dependencies

- utilities/rest/queuing/signAndBroadcast.go
Closes: #XXXX
---
I have...
I have...
> updating sign and broadcast for updated flow

- utilities/rest/sign/response.go
Closes: #XXXX
---
I have...
I have...
> changing outdated Tx

- buf.gen.yaml
- buf.yaml
- schema/data/base/accAddressData.v1.proto
- schema/data/base/booleanData.v1.proto
- schema/data/base/data.v1.proto
- schema/data/base/decData.v1.proto
- schema/data/base/heightData.v1.proto
- schema/data/base/idData.v1.proto
- schema/data/base/stringData.v1.proto
- schema/ids/base/assetID.v1.proto
- schema/ids/base/classificationID.v1.proto
- schema/ids/base/dataID.v1.proto
- schema/ids/base/hashID.v1.proto
- schema/ids/base/id.v1.proto
- schema/ids/base/identityID.v1.proto
- schema/ids/base/maintainerID.v1.proto
- schema/ids/base/orderID.v1.proto
- schema/ids/base/ownableID.v1.proto
- schema/ids/base/propertyID.v1.proto
- schema/ids/base/splitID.v1.proto
- schema/ids/base/stringID.v1.proto
- schema/types/base/height.v1.proto
Closes: #XXXX
---
I have...
I have...
> adding proto files for ids

- buf.gen.yaml
- buf.yaml
- schema/data/base/accAddressData.v1.proto
- schema/data/base/booleanData.v1.proto
- schema/data/base/data.v1.proto
- schema/data/base/decData.v1.proto
- schema/data/base/heightData.v1.proto
- schema/data/base/idData.v1.proto
- schema/data/base/stringData.v1.proto
Closes: #XXXX
---
I have...
I have...
> adding buf support and proto files for data

- schema/data/base/idData.go
- schema/lists/base/List.v1.proto
- schema/lists/base/dataList.go
- schema/lists/base/dataList.v1.proto
- schema/lists/base/deprecatedList.go
- schema/lists/base/idList.go
- schema/lists/base/idList.v1.proto
- schema/lists/base/list.go
- schema/lists/base/propertyList.go
- schema/lists/base/propertyList.v1.proto
- schema/lists/dataList.go
- schema/lists/idList.go
- schema/lists/propertyList.go
- schema/properties/base/mesaProperty.go
- schema/properties/base/mesaProperty.v1.proto
- schema/properties/base/metaProperty.go
- schema/properties/base/metaProperty.v1.proto
- schema/properties/base/property.go
- schema/properties/base/property.v1.proto
- schema/properties/metaProperty.go
- schema/properties/property.go
Closes: #XXXX
---
I have...
I have...
> proto implementation for lists

- modules/assets/internal/transactions/burn/transaction.go
- modules/assets/internal/transactions/define/transaction.go
- modules/assets/internal/transactions/deputize/transaction.go
- modules/assets/internal/transactions/mint/transaction.go
- modules/assets/internal/transactions/mutate/transaction.go
- modules/assets/internal/transactions/renumerate/transaction.go
- modules/assets/internal/transactions/revoke/transaction.go
- modules/identities/internal/transactions/define/transaction.go
- modules/identities/internal/transactions/deputize/transaction.go
- modules/identities/internal/transactions/issue/transaction.go
- modules/identities/internal/transactions/mutate/transaction.go
- modules/identities/internal/transactions/nub/transaction.go
- modules/identities/internal/transactions/provision/transaction.go
- modules/identities/internal/transactions/quash/transaction.go
- modules/identities/internal/transactions/revoke/transaction.go
- modules/identities/internal/transactions/unprovision/transaction.go
- modules/metas/internal/transactions/reveal/transaction.go
- modules/orders/internal/transactions/cancel/transaction.go
- modules/orders/internal/transactions/define/transaction.go
- modules/orders/internal/transactions/deputize/transaction.go
- modules/orders/internal/transactions/immediate/transaction.go
- modules/orders/internal/transactions/make/transaction.go
- modules/orders/internal/transactions/modify/transaction.go
- modules/orders/internal/transactions/revoke/transaction.go
- modules/orders/internal/transactions/take/transaction.go
- modules/splits/internal/transactions/send/transaction.go
- modules/splits/internal/transactions/unwrap/transaction.go
- modules/splits/internal/transactions/wrap/transaction.go
Closes: #XXXX
---
I have...
I have...
> feat(transaction): adding placeHolder service and grpcGateway registerars till grpc impl

- schema/documents/base/classification_test.go
- schema/documents/base/maintainer_test.go
- schema/documents/base/order_test.go
- schema/helpers/base/storeKeyPrefix_test.go
- schema/ids/base/ownableID_test.go
- schema/ids/base/splitID_test.go
- schema/ids/utilities/id_test.go
Closes: #XXXX
---
I have...
I have...
> Add tests for schema Newly Added Files

- schema/documents/base/document.go
- schema/documents/base/document_test.go
- schema/documents/document.go
- schema/ids/base/assetID_test.go
- schema/ids/base/classificationID_test.go
- schema/ids/base/identityID_test.go
- schema/ids/base/maintainerID_test.go
- schema/ids/base/orderID_test.go
- schema/lists/base/dataList.go
- schema/lists/base/dataList_test.go
- schema/lists/base/idList.go
- schema/lists/base/idList_test.go
- schema/lists/base/list.go
- schema/lists/base/list_test.go
- schema/lists/base/propertyList.go
- schema/lists/base/propertyList_test.go
- schema/lists/dataList.go
- schema/lists/idList.go
- schema/lists/list.go
- schema/lists/propertyList.go
Add Sanitize() method for documents
Closes: #XXXX
---
I have...
I have...
correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR …
> fix(schema): add sanitize method for documents

- schema/properties/base/anyProperty.go
Closes: #XXXX
---
I have...
I have...
> property impls for getters

- schema/data/base/anyData.go
Closes: #XXXX
---
I have...
I have...
> feat(data): implementing getter interface

- modules/metas/internal/queries/meta/response.go
- schema/helpers/base/mapper.go
Closes: #XXXX
---
I have...
I have...
> feat(mapper): implementing usage of base codec

- schema/applications/base/application.go
Closes: #XXXX
---
I have...
I have...
> making mantleNode work on  ~/.mantleNode/config

- schema/applications/base/application.go
- utilities/rest/initializer.go
Closes: #XXXX
---
I have...
I have...
> registering rest routes

- modules/assets/internal/genesis/prototype_test.go
- modules/assets/prototype_test.go
- modules/classifications/internal/genesis/prototype_test.go
- modules/classifications/prototype_test.go
- modules/identities/internal/genesis/prototype_test.go
- modules/identities/prototype_test.go
- modules/maintainers/internal/genesis/prototype_test.go
- modules/maintainers/prototype_test.go
- modules/metas/internal/genesis/prototype_test.go
- modules/metas/prototype_test.go
- modules/orders/internal/genesis/prototype_test.go
- modules/orders/prototype_test.go
- modules/splits/internal/genesis/prototype_test.go
- modules/splits/prototype_test.go
removing prototype test errors
NOTE: These tests are not valid yet
Closes: #XXXX
---
I have...
I have...
correct [type prefix](https://github.com/commitizen/conventional-commit-types/blo …
> adding more fixes

- modules/assets/internal/transactions/burn/message_test.go
- modules/assets/internal/transactions/burn/transactionRequest_test.go
- modules/assets/internal/transactions/define/message_test.go
- modules/assets/internal/transactions/define/transactionRequest_test.go
- modules/assets/internal/transactions/deputize/message_test.go
- modules/assets/internal/transactions/deputize/transactionRequest_test.go
- modules/assets/internal/transactions/mint/message_test.go
- modules/assets/internal/transactions/mint/transactionRequest_test.go
- modules/assets/internal/transactions/mutate/message_test.go
- modules/assets/internal/transactions/mutate/transactionRequest_test.go
- modules/assets/internal/transactions/renumerate/message_test.go
- modules/assets/internal/transactions/revoke/message_test.go
- modules/assets/internal/transactions/revoke/transactionRequest_test.go
- modules/identities/internal/transactions/define/transactionRequest_test.go
- modules/identities/internal/transactions/nub/transactionRequest_test.go
- modules/identities/internal/transactions/provision/transactionRequest_test.go
- modules/identities/internal/transactions/quash/transactionRequest_test.go
- modules/identities/internal/transactions/revoke/transactionRequest_test.go
- modules/identities/internal/transactions/unprovision/transactionRequest_test.go
- modules/splits/internal/transactions/send/transactionRequest_test.go
- modules/splits/internal/transactions/unwrap/transactionRequest_test.go
Closes: #XXXX
---
I have...
I have...
> all visible errors removed from modules

- schema/documents/base/classification_test.go
- schema/ids/base/propertyID.go
- schema/ids/propertyID.go
- schema/properties/base/mesaProperty_test.go
- schema/properties/base/metaProperty_test.go
Closes: #XXXX
---
I have...
I have...
> fixing and adding tests for properties

- modules/assets/internal/transactions/mint/transactionKeeper.go
- modules/assets/internal/transactions/mint/transactionKeeper_test.go
- modules/identities/internal/transactions/issue/transactionKeeper.go
- modules/identities/internal/transactions/quash/transactionKeeper.go
- modules/orders/internal/transactions/immediate/transactionKeeper.go
- modules/orders/internal/transactions/make/transactionKeeper.go
- schema/applications/base/application.go
Closes: #XXXX
---
I have...
I have...
> cleaning code

- modules/maintainers/auxiliaries/deputize/keeper.go
- modules/maintainers/internal/parameters/deputizeAllowed/parameter.go
- modules/maintainers/internal/parameters/deputizeAllowed/parameter_test.go
- modules/maintainers/internal/parameters/prototype.go
- modules/maintainers/internal/parameters/prototype_test.go
- modules/maintainers/internal/simulator/genesis.go
- modules/maintainers/internal/simulator/params.go
- schema/properties/constants/properties.go
Closes: #XXXX
---
I have...
I have...
> feat(maintainers): defining and implementing deputizeAllowed parameter

- modules/metas/internal/parameters/prototype.go
- modules/metas/internal/parameters/prototype_test.go
- modules/metas/internal/parameters/revealEnabled/parameter.go
- modules/metas/internal/parameters/revealEnabled/parameter_test.go
- modules/metas/internal/simulator/genesis.go
- modules/metas/internal/simulator/params.go
- modules/metas/internal/transactions/reveal/transactionKeeper.go
- schema/properties/constants/properties.go
Closes: #XXXX
---
I have...
I have...
> feat(metas): defining and implementing RevealEnabled parameter

- schema/ids/base/coinID.go
Closes: #XXXX
---
I have...
I have...
> fixing a bug

- utilities/rest/idGetters/docs/asset.go
- utilities/rest/idGetters/docs/common.go
- utilities/rest/idGetters/docs/identity.go
- utilities/rest/idGetters/docs/order.go
- utilities/rest/idGetters/docs/request.go
- utilities/rest/idGetters/docs/response.go
- utilities/rest/idGetters/docs/split.go
- utilities/rest/idGetters/transactionRequest.go
Closes: #XXXX
---
I have...
I have...
> adding id getters

- modules/assets/internal/key/key.go
- modules/classifications/auxiliaries/define/keeper.go
- modules/classifications/internal/key/key.go
- modules/classifications/internal/simulator/genesis.go
- modules/identities/internal/key/key.go
- modules/maintainers/internal/key/key.go
- modules/metas/internal/key/key.go
- modules/orders/internal/key/key.go
- modules/splits/internal/key/key.go
- schema/applications/base/application.go
Closes: #XXXX
---
I have...
I have...
> adding prototype in Key and fixing address fetch for validators

- schema/ids/base/anyID.go
- schema/ids/base/anyOwnableID.go
- schema/ids/base/assetID.go
- schema/ids/base/classificationID.go
- schema/ids/base/coinID.go
- schema/ids/base/dataID.go
- schema/ids/base/hashID.go
- schema/ids/base/identityID.go
- schema/ids/base/maintainerID.go
- schema/ids/base/orderID.go
- schema/ids/base/propertyID.go
- schema/ids/base/splitID.go
- schema/ids/base/stringID.go
- schema/ids/base/stringID_test.go
- schema/ids/constansts/regularExpressions.go
- schema/ids/id.go
- schema/ids/utilities/regularExpressions.go
Closes: #XXXX
---
I have...
I have...
> adding validation for ids

- schema/properties/base/mesaProperty.go
- schema/properties/base/metaProperty.go
Closes: #XXXX
---
I have...
I have...
> validation for properties

- schema/lists/base/idList.go
- schema/lists/base/propertyList.go
- schema/lists/idList.go
- schema/lists/propertyList.go
Closes: #XXXX
---
I have...
I have...
> validation for lists

- schema/data/base/decData_test.go
- schema/data/base/listData.go
- schema/data/base/listData_test.go
Closes: #XXXX
---
I have...
I have...
> listData will no longer contain listData

- modules/identities/internal/transactions/issue/transactionKeeper.go
- modules/orders/internal/transactions/immediate/message.go
- modules/orders/internal/transactions/make/message.go
- modules/orders/internal/transactions/modify/message.go
- modules/orders/internal/transactions/take/message.go
- modules/splits/internal/transactions/send/message.go
- modules/splits/internal/transactions/unwrap/message.go
- schema/data/base/decData.go
- schema/data/base/decData_test.go
- schema/types/base/split.go
Closes: #XXXX
---
I have...
I have...
> Removing sortableDec limitation

- modules/assets/internal/transactions/define/transactionKeeper.go
- modules/assets/internal/transactions/mint/transactionKeeper.go
- modules/assets/internal/transactions/mutate/transactionKeeper.go
- modules/identities/internal/transactions/define/transactionKeeper.go
- modules/identities/internal/transactions/issue/transactionKeeper.go
- modules/identities/internal/transactions/mutate/transactionKeeper.go
- modules/orders/internal/transactions/define/transactionKeeper.go
- modules/orders/internal/transactions/immediate/transactionKeeper.go
- modules/orders/internal/transactions/make/transactionKeeper.go
Closes: #XXXX
---
I have...
I have...
> changing append to add

- go.sum
Closes: #XXXX
---
I have...
I have...
> bump(schema)

- x/assets/queries/asset/query_request.pb.go
Closes: #XXXX
---
I have...
I have...
> fix: proto generate

- go.mod
- go.sum
Closes: #XXXX
---
I have...
I have...
> bump: schema

- x/assets/transactions/mutate/transactionKeeper.go
> fix(assets): incorrect error nil check

- x/orders/transactions/immediate/message.go
- x/orders/transactions/immediate/transactionRequest.go
- x/orders/transactions/modify/message.go
- x/orders/transactions/modify/transactionRequest.go
- x/splits/transactions/send/message.go
- x/splits/transactions/send/transactionRequest.go
- x/splits/transactions/unwrap/message.go
- x/splits/transactions/unwrap/transactionRequest.go
Closes: #370
---
I have...
I have...
> fix(splits,orders): message field expecting dec, should be int

- utilities/rest/faucet/configuration.go
- utilities/rest/faucet/handler.go
- utilities/rest/initializer.go
- x/orders/transactions/make/message.go
Closes: #XXXX
---
I have...
I have...
> faucet and orders make validation fix

- x/splits/auxiliaries/prototype.go
Closes: #XXXX
---
I have...
I have...
> fix(auxiliaries): minor import fix

- x/classifications/auxiliaries/define/auxiliary_keeper.go
Closes: #XXXX
---
I have...
I have...
> Fixing error message

- utilities/rest/queuing/broadcast.go
Closes: #XXXX
---
I have...
I have...
> chore(rest): minor optimizations to broadcast utility

- x/classifications/auxiliaries/define/auxiliary_keeper.go
Closes: #XXXX
---
I have...
I have...
> Correcting bond amount in default case

- x/classifications/auxiliaries/conform/auxiliary_keeper.go
…quest
Closes: #XXXX
---
I have...
I have...
> Correcting conform auxiliary check for nil mutables and immutables request
